release-date = "2022-07-13"

[[entries]]
id = "4fddaa0d-7e32-486e-a886-22098cdec886"
type = "improvement"
description = "color-format logging"
author = "@NiklasRosenstein"

[[entries]]
id = "4084c216-58b2-4bfa-9dfa-4a1d4464f8c2"
type = "feature"
description = "add `-q,--quiet` flag to Kraken commands"
author = "@NiklasRosenstein"

[[entries]]
id = "13f6e35b-5027-433a-be97-5686b7ed1c5b"
type = "feature"
description = "add `kraken query` command"
author = "@NiklasRosenstein"
