release-date = "2022-07-18"

[[entries]]
id = "8d8597ea-991f-4d7a-a0ef-412a284605ba"
type = "breaking change"
description = "move `kraken.cli.executor` module to `kraken-core`"
author = "@NiklasRosenstein"
