release-date = "2022-07-21"

[[entries]]
id = "5f72a0e8-5682-4854-bc7a-1c552d7c1e02"
type = "improvement"
description = "Sort keys in `.kraken.lock` file (close #6)"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/kraken-build/kraken-cli/issues/6",
]
