[[entries]]
id = "0e7fbd83-bf88-43f0-bcca-1e372a3f8a4f"
type = "feature"
description = "add `-0,--allow-no-tasks` option that allows no tasks to be selected to `kraken run` command"
author = "@NiklasRosenstein"
