[[entries]]
id = "1139263d-9dc9-4e38-87ba-7e00ad709047"
type = "breaking change"
description = "remove CLI aliases for `fmt`, `lint`, `test` and `build`, move introspecting commands into `kraken q` group, the `kraken query --is-up-to-date` function is now available as `kraken q is-up-to-date`"
author = "@NiklasRosenstein"
