[[entries]]
id = "a72629f7-6cf0-476d-87d1-be185745f1a4"
type = "improvement"
description = "Do not error if no tasks were selected if the `-s,--skip-build` option is passed to `kraken run`"
author = "@NiklasRosenstein"
