[[entries]]
id = "c4bfa201-751f-411d-a303-ef52d1a6f569"
type = "improvement"
description = "calculate table column with in `kraken ls` command instead of using a fixed 32 characters"
author = "@NiklasRosenstein"
